spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bsep
    username: postgres
    password: super
    driver-class-name: org.postgresql.Driver
  server:
    port: 8080
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        fromat_sql: true
    database: postgresql
    database-platfrom: org.hibernate.dialect.PostgreSQLDialect

